# Generated by Django 4.1 on 2022-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoshare',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
